name: Production Environment Workflow Caller

on:
  push:
    branches: main
  pull_request:
    branches: main
    types: [closed]

jobs:
  run_ci_prod:
    uses: ./.github/workflows/workflow-ci.yml
    secrets: inherit
    with:
      target: prod
    outputs:
      artifact_id: ${{ steps.generate_and_push.outputs.artifact_id }}

  run_cd_prod:
    needs: run_ci_prod    
    uses: ./.github/workflows/workflow-cd.yml
    secrets: inherit
    with:
      target: prod
      artifact_id: ${{ needs.run_ci_prod.outputs.artifact_id }}
        

      